/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IExchangeContract {
  export type DynamicExchangeRateStruct = { max_inflow_amount: BigNumberish };

  export type DynamicExchangeRateStructOutput = [max_inflow_amount: bigint] & {
    max_inflow_amount: bigint;
  };

  export type ConfigResponseStruct = {
    from_asset: AssetLib.ResolvedAssetStruct;
    to_asset: AssetLib.ResolvedAssetStruct;
    exchange_rate_bps: BigNumberish;
    exchanged_amount: BigNumberish;
    amount: BigNumberish;
    start_time: BigNumberish;
    end_time: BigNumberish;
    recipient: RecipientLib.RecipientStruct;
  };

  export type ConfigResponseStructOutput = [
    from_asset: AssetLib.ResolvedAssetStructOutput,
    to_asset: AssetLib.ResolvedAssetStructOutput,
    exchange_rate_bps: bigint,
    exchanged_amount: bigint,
    amount: bigint,
    start_time: bigint,
    end_time: bigint,
    recipient: RecipientLib.RecipientStructOutput
  ] & {
    from_asset: AssetLib.ResolvedAssetStructOutput;
    to_asset: AssetLib.ResolvedAssetStructOutput;
    exchange_rate_bps: bigint;
    exchanged_amount: bigint;
    amount: bigint;
    start_time: bigint;
    end_time: bigint;
    recipient: RecipientLib.RecipientStructOutput;
  };

  export type ExchangeContractInitParamsStruct = {
    owner: AddressLike;
    from_asset: AssetLib.AssetStruct;
    to_asset: AssetLib.AssetStruct;
    recipient: RecipientLib.RecipientStruct;
    exchange_rate_bps: BigNumberish;
    schedule: ScheduleLib.ScheduleStruct;
  };

  export type ExchangeContractInitParamsStructOutput = [
    owner: string,
    from_asset: AssetLib.AssetStructOutput,
    to_asset: AssetLib.AssetStructOutput,
    recipient: RecipientLib.RecipientStructOutput,
    exchange_rate_bps: bigint,
    schedule: ScheduleLib.ScheduleStructOutput
  ] & {
    owner: string;
    from_asset: AssetLib.AssetStructOutput;
    to_asset: AssetLib.AssetStructOutput;
    recipient: RecipientLib.RecipientStructOutput;
    exchange_rate_bps: bigint;
    schedule: ScheduleLib.ScheduleStructOutput;
  };
}

export declare namespace IContractBase {
  export type AdoTypeResponseStruct = { ado_type: string };

  export type AdoTypeResponseStructOutput = [ado_type: string] & {
    ado_type: string;
  };

  export type VersionResponseStruct = { version: string };

  export type VersionResponseStructOutput = [version: string] & {
    version: string;
  };
}

export declare namespace AmpMsgLib {
  export type AmpPktCtxStruct = {
    origin: AddressLike;
    previous_sender: AddressLike;
  };

  export type AmpPktCtxStructOutput = [
    origin: string,
    previous_sender: string
  ] & { origin: string; previous_sender: string };

  export type AmpPktStruct = {
    message: BytesLike;
    funds: BigNumberish;
    ctx: AmpMsgLib.AmpPktCtxStruct;
  };

  export type AmpPktStructOutput = [
    message: string,
    funds: bigint,
    ctx: AmpMsgLib.AmpPktCtxStructOutput
  ] & { message: string; funds: bigint; ctx: AmpMsgLib.AmpPktCtxStructOutput };
}

export declare namespace RecipientLib {
  export type RecipientStruct = { recipient: string; message: BytesLike };

  export type RecipientStructOutput = [recipient: string, message: string] & {
    recipient: string;
    message: string;
  };
}

export declare namespace AssetLib {
  export type ResolvedAssetStruct = { native: string; smart: AddressLike };

  export type ResolvedAssetStructOutput = [native: string, smart: string] & {
    native: string;
    smart: string;
  };

  export type AssetStruct = { native: string; smart: string };

  export type AssetStructOutput = [native: string, smart: string] & {
    native: string;
    smart: string;
  };
}

export declare namespace ScheduleLib {
  export type ExpiryStruct = {
    from_now: BigNumberish;
    at_time: BigNumberish;
    infinite: boolean;
  };

  export type ExpiryStructOutput = [
    from_now: bigint,
    at_time: bigint,
    infinite: boolean
  ] & { from_now: bigint; at_time: bigint; infinite: boolean };

  export type ScheduleStruct = {
    start: ScheduleLib.ExpiryStruct;
    end: ScheduleLib.ExpiryStruct;
  };

  export type ScheduleStructOutput = [
    start: ScheduleLib.ExpiryStructOutput,
    end: ScheduleLib.ExpiryStructOutput
  ] & {
    start: ScheduleLib.ExpiryStructOutput;
    end: ScheduleLib.ExpiryStructOutput;
  };
}

export interface ExchangeContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "add_funds_erc20"
      | "add_funds_erc20_dynamic"
      | "add_funds_native"
      | "add_funds_native_dynamic"
      | "ado_type"
      | "ampReceive"
      | "buy_with_erc20"
      | "buy_with_erc20_with_recipient"
      | "buy_with_native"
      | "buy_with_native_with_recipient"
      | "cancel_sale"
      | "config"
      | "implementation"
      | "initialize"
      | "proxiableUUID"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AdoDefaultInitialized" | "Initialized" | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "add_funds_erc20",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "add_funds_erc20_dynamic",
    values: [BigNumberish, IExchangeContract.DynamicExchangeRateStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "add_funds_native",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "add_funds_native_dynamic",
    values: [IExchangeContract.DynamicExchangeRateStruct]
  ): string;
  encodeFunctionData(functionFragment: "ado_type", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ampReceive",
    values: [AmpMsgLib.AmpPktStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "buy_with_erc20",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buy_with_erc20_with_recipient",
    values: [BigNumberish, RecipientLib.RecipientStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "buy_with_native",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buy_with_native_with_recipient",
    values: [RecipientLib.RecipientStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel_sale",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [IExchangeContract.ExchangeContractInitParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_funds_erc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_funds_erc20_dynamic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_funds_native",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_funds_native_dynamic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ado_type", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ampReceive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buy_with_erc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buy_with_erc20_with_recipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buy_with_native",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buy_with_native_with_recipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancel_sale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AdoDefaultInitializedEvent {
  export type InputTuple = [
    adoType: string,
    version: string,
    adoOwner: AddressLike
  ];
  export type OutputTuple = [
    adoType: string,
    version: string,
    adoOwner: string
  ];
  export interface OutputObject {
    adoType: string;
    version: string;
    adoOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExchangeContract extends BaseContract {
  connect(runner?: ContractRunner | null): ExchangeContract;
  waitForDeployment(): Promise<this>;

  interface: ExchangeContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  add_funds_erc20: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  add_funds_erc20_dynamic: TypedContractMethod<
    [
      amount: BigNumberish,
      dynamic_exchange_rate: IExchangeContract.DynamicExchangeRateStruct
    ],
    [void],
    "nonpayable"
  >;

  add_funds_native: TypedContractMethod<[], [void], "payable">;

  add_funds_native_dynamic: TypedContractMethod<
    [dynamic_exchange_rate: IExchangeContract.DynamicExchangeRateStruct],
    [void],
    "payable"
  >;

  ado_type: TypedContractMethod<
    [],
    [IContractBase.AdoTypeResponseStructOutput],
    "view"
  >;

  ampReceive: TypedContractMethod<
    [packet: AmpMsgLib.AmpPktStruct],
    [void],
    "payable"
  >;

  buy_with_erc20: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "payable"
  >;

  buy_with_erc20_with_recipient: TypedContractMethod<
    [amount: BigNumberish, recipient: RecipientLib.RecipientStruct],
    [bigint],
    "payable"
  >;

  buy_with_native: TypedContractMethod<[], [bigint], "payable">;

  buy_with_native_with_recipient: TypedContractMethod<
    [recipient: RecipientLib.RecipientStruct],
    [bigint],
    "payable"
  >;

  cancel_sale: TypedContractMethod<[], [void], "nonpayable">;

  config: TypedContractMethod<
    [],
    [IExchangeContract.ConfigResponseStructOutput],
    "view"
  >;

  implementation: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [params: IExchangeContract.ExchangeContractInitParamsStruct],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  version: TypedContractMethod<
    [],
    [IContractBase.VersionResponseStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "add_funds_erc20"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "add_funds_erc20_dynamic"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      dynamic_exchange_rate: IExchangeContract.DynamicExchangeRateStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_funds_native"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "add_funds_native_dynamic"
  ): TypedContractMethod<
    [dynamic_exchange_rate: IExchangeContract.DynamicExchangeRateStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "ado_type"
  ): TypedContractMethod<
    [],
    [IContractBase.AdoTypeResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "ampReceive"
  ): TypedContractMethod<[packet: AmpMsgLib.AmpPktStruct], [void], "payable">;
  getFunction(
    nameOrSignature: "buy_with_erc20"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "buy_with_erc20_with_recipient"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: RecipientLib.RecipientStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "buy_with_native"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "buy_with_native_with_recipient"
  ): TypedContractMethod<
    [recipient: RecipientLib.RecipientStruct],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancel_sale"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "config"
  ): TypedContractMethod<
    [],
    [IExchangeContract.ConfigResponseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [params: IExchangeContract.ExchangeContractInitParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<
    [],
    [IContractBase.VersionResponseStructOutput],
    "view"
  >;

  getEvent(
    key: "AdoDefaultInitialized"
  ): TypedContractEvent<
    AdoDefaultInitializedEvent.InputTuple,
    AdoDefaultInitializedEvent.OutputTuple,
    AdoDefaultInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdoDefaultInitialized(string,string,address)": TypedContractEvent<
      AdoDefaultInitializedEvent.InputTuple,
      AdoDefaultInitializedEvent.OutputTuple,
      AdoDefaultInitializedEvent.OutputObject
    >;
    AdoDefaultInitialized: TypedContractEvent<
      AdoDefaultInitializedEvent.InputTuple,
      AdoDefaultInitializedEvent.OutputTuple,
      AdoDefaultInitializedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
